# Generated by Django 4.2.29 on 2026-03-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_record_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='main.subcategory', verbose_name='Подкатегория'),
        ),
    ]
